version: "3"

services:
  uptimerobot-page:
    image: giuem/uptimerobot-page
    # build: .
    environment: 
      - PORT=3000
      - LOG_LEVEL=info
      - CRON_TIME="*/1 * * * *"
      - UPTIME_ROBOT_API=
      - UPTIME_ROBOT_NAME_PATTERN=%group/%name
      - WEBSITE_TITLE=
      - WEBSITE_COPYRIGHT=
    ports: 
      - 127.0.0.1:8082:3000
